# Header
menu:
  Home: /
  Projects: /projects
  #Meetings: /meetings
  #Forum: https://github.com/codeforokc/discussions/issues
  #Chat: https://gitter.im/codeforokc/discussions
  #Join Us: /join-us
  #Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
